# Generated by Django 5.2.17 on 2026-09-22 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0002_analysisresult_all_findings_analysisresult_insights_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('lab_result', 'Lab/Test Result'), ('prescription', 'Prescription'), ('certificate', 'Medical Certificate'), ('scan', 'Scan/Imaging'), ('other', 'Other')], default='other', max_length=50)),
                ('file', models.FileField(upload_to='documents/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
